### ISSUE TITLE
Download for S3 Glacier Archive is not functional. 

### ISSUE THREAD

**Issue by Vetavize-Robert** [cloudback/issue-tracker#29] opened 2024-06-28 17:47 UTC
**Describe the bug**
I get an error if I try and download an archive from S3 Glacier.

**To Reproduce**
1. Go to the dashboard https://app.cloudback.it/
2. Click the download icon for a S3 Glacier archive

**Expected behavior**
Archive downloads

**Screenshots**

![image](https://github.com/cloudback/issue-tracker/assets/169933777/fba3b885-1dac-40e0-ab11-03739e864d36)

![image](https://github.com/cloudback/issue-tracker/assets/169933777/ba187e67-de89-4359-bafc-4fbabda3fc0d)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome
- Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by arxange1** [comment] 2024-06-28 18:12
Dear @Vetavize-Robert,

We are currently experiencing a partial service downgrade due to recent infrastructure changes. To resolve this issue, we will be shutting down the entire site today. We will notify you as soon as the issue is resolved.

Additionally, you can check the service health reports on the status page:
* https://docs.cloudback.it/status/

**Comment by arxange1** [comment] 2024-06-28 23:33
Dear @Vetavize-Robert, the maintenance is done. the system is fully operational, please check

**Comment by arxange1** [comment] 2024-06-28 23:57
The issue with S3 Glacier Archive downloads is unrelated to maintenance. The problem is due to an incorrect error message being displayed. Please note that retrieving an S3 Glacier Archive can take up to 48 hours, so instant downloads are not supported for this type of storage. We are currently working on a fix to display the correct message.

**Comment by arxange1** [comment] 2024-06-29 01:16
The fix is implemented, please check

**Comment by Vetavize-Robert** [comment] 2024-07-16 21:23
It does not look like it is resolved. 

![image](https://github.com/user-attachments/assets/53a20293-d49d-4b77-8e72-acd16370d88c)

While I understand given that it is S3 Glacier there is no way to make it an instant download, I do not see a path to get a download through your service. Perhaps an email with a link to the download when available or another notification?

**Comment by arxange1** [comment] 2024-07-16 21:33
Dear @Vetavize-Robert, thank you for understanding the nature of the S3 Glacier and the associated download delays. The current setup doesn’t allow for downloads, and we’re sorry for any inconvenience this causes.

To better assist you, please provide more details on how you plan to use the download feature and why the S3 Glacier dashboard does not meet your needs.

**Comment by Vetavize-Robert** [comment] 2024-07-16 21:50
S3 Glacier offers the lowest storage cost for our backups that are still 100% under our control. While we only anticipate downloading in an emergency event, we do need to test that our processes work from time to time. We would like to download the file, recover it to a new GitHub, and check to make sure that everything works. Since the zip file is password protected (your service has the password), I would expect that the download would queue, then when the download is ready we would get a link to the zip file with the appropriate password.

**Comment by arxange1** [comment] 2024-07-16 22:07
To address the password issue, we can add a "Send password via email" option to the "Cannot download backup archive" dialog, as a quick fix. Please let us know if that will work for you.

To address the testing needs, you can restore the backup to a new test repository to ensure everything works as expected, instead of downloading the archive manually.

Also, please note that in case of an emergency, initiating the download process from S3 Glacier can take up to 48 hours, which might not be ideal for urgent situations.

**Comment by Vetavize-Robert** [comment] 2024-07-17 01:38
Adding the password via email is a good stopgap solution. The likelihood that an event would occur that would require us to get a backup from your solution is unlikely, so keeping our storage costs as low as possible is our goal. The idea behind S3 was that if your service ever went down, we have a copy under our control that we can restore. This does bring up the point that we should probably store the backup in S3 without a password just in case your service goes down and we cannot get the password.

Here is our backup mentality with your service:

1. Primary Path:
  a. Store backup via Cloudback US
  b. Retrieval is fast and on a site not associated with our primary service
2. Secondary Path:
  a. S3 Glacier Backup
  b. Storage is cheap
  c. Backup is under our control
  d. Long term storage for future audits (7 year retention period)

Initially we thought that composite storage would allow us to select Cloudback as the Primary and S3 as the secondary. It does not allow us to do that, so for the time being I am just going to take S3 snapshots manually.

**Comment by arxange1** [comment] 2024-07-17 12:56
Thank you for providing the details. We will allow Cloudback-managed storage to serve as a primary target in a composite storage setup. Consequently, we anticipate the release of two new features:
- A "send password" link
- Integration of Cloudback-managed storage in composite storage setups

We will notify you once these features are available.

**Comment by Vetavize-Robert** [comment] 2024-07-17 20:11
Thank you! You are doing an excellent job.

**Comment by arxange1** [comment] 2024-07-18 20:39
Dear @Vetavize-Robert, 
We implemented an option to choose Cloudback storage as a primary target in a composite storage setup. Once configured, it will allow you to download an archive and receive a password email. Please check.

A "send password" link for S3 Glacier will be released within a month. We will let you know as soon as it is released.

**Comment by Vetavize-Robert** [comment] 2024-07-22 03:57
The new composite configuration is great and works as intended. Thank you for the enhancement.

**Comment by arxange1** [comment] 2024-08-05 07:46
Dear @Vetavize-Robert, 
A "send password" link for S3 Glacier is implemented, please check.

**Comment by Vetavize-Robert** [comment] 2024-08-06 15:33
Download works, Slight translation issue:

> The storage does not support instant downloads. You can request the password to access the archive contents after downloading it from your storage by your own:


Should be:
Replace `This storage type` with the type of storage, for example "S3", or just use "this storage type" if you want to keep it generic. 
"by your own" should be "on your own". 

> `This storage type` does not support instant downloads. You can request the password to access the archive contents after downloading it from your storage on your own:


Thinking about it more you may want something like this for clarity:


> `This storage type` does not support instant downloads.  You will need to download the archive from your own storage solution.
> 
> For security reasons this backup is password protected. You will receive **an email** with the password after clicking **Send Password** button.
> 
> [Send Password]

The received email has the minimum necessary information for the filename and password. It may be nice to also have the repo name. If your user has a few repos and requests in a row, the repo name will help untangle things.

**Comment by arxange1** [comment] 2024-08-06 21:36
Dear @Vetavize-Robert,

We have implemented the suggested changes. Please review them. We greatly appreciate your contribution.

**Closed** 2024-08-21 13:34 UTC
Labels: bug, done
